### PR TITLE
Added Spanish (es) translations. Edited gulpfile.ls config file to add S...

### PR DESCRIPTION
**Pull request by RubenDjOn**
...panish language.

Hi, 

I want to translate the game to Spanish (Spain). I've added the json files needed and also changed the gulpfile.ls file.

Let me know if everything is ok and if the commit to the "dev" branch is also correct.

### CODE REVIEW

**Comment by SomeHats** [comment]
This look great - can't wait to see the rest of your translation :+1:

**Comment by RubenDjOn** [comment]
Ok. I've added new translations and also added the Spanish button to index and paused menu.

I have a question about github. I didn't make any new pull request, and the commits made to my repo has been "pushed" to this pull request. Why is this happening?

**Comment by SomeHats** [comment]
Sure. So you see at the top of the page where it says

> RubenDjOn wants to merge 3 commits into `drumrollhq:dev` from `RubenDjOn:dev`

That means that this pull request is from one branch (the `dev` branch of https://github.com/RubenDjOn/E.A.K.) in to `dev` branch of this repo. Because pull requests on github are always between two branches rather than an explicit list of commits, as you push more commits to your branch they'll automatically show up here.

**Comment by RubenDjOn** [comment]
Ok. So if you don't merge this pull request, every commit that I make to my fork, will be automatically show up in this pull request.

Thanks for the explanation.

**Pull request closed without merging**
